# Soll die Live API oder Sandbox AP benutzt werden?
# True -> Live API
# False -> Sandbox
LiveModus: True

# nur auf Anforderung ändern
Debug: True

# PayPal API Dokumentation:
# https://developer.paypal.com/api/payments/v2/#captures_refund
SandBoxAPI:
  BaseUrl: 'https://api-m.sandbox.paypal.com'
  EndPoint_Token: '/v1/oauth2/token'
  EndPoint_Payments: '/v2/payments/captures/{capture_id}/refund'

LiveAPI:
  BaseUrl: 'https://api-m.paypal.com'
  EndPoint_Token: '/v1/oauth2/token'
  EndPoint_Payments: '/v2/payments/captures/{capture_id}/refund'

